extra_safety_buffer: 0.1   # meters

aux_clean_map:
  track_unknown_space: false
  footprint: [[0.15, 0.15], [-0.15, 0.15], [-0.15, -0.15], [0.15, -0.15]]
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  always_send_full_costmap: false
  
  plugins: 
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: costmap_prohibition_layer,       type: "movel_costmap_2d::CostmapProhibitionLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/map_nav"
    subscribe_to_updates: false

  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 4.0

aux_sync_map:
  track_unknown_space: false
  footprint: [[0.15, 0.15], [-0.15, 0.15], [-0.5, -0.15], [0.15, -0.15]]
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  always_send_full_costmap: true
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: "/move_base/global_costmap/costmap"
    subscribe_to_updates: true

  inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 4.0
  
circumcribed_threshold: 128

# aux_clean_planner:
#   neutral_cost: 66
#   cost_factor: 0.55
#   lethal_cost: 253
#   allow_unknown: false

# aux_sync_planner:
#   neutral_cost: 66
#   cost_factor: 0.55
#   lethal_cost: 253
#   allow_unknown: false
