# Extra parameters for movel_move_base (only used if environment MOVEL_MOVE_BASE=true)

#stop_at_obstacle: true #set this param on movel_redis/global_variables.yaml - stop_at_obstacles_enabled
stop_at_obstacle_distance: 1.5
obstacle_clearing_timeout: -1.0
allow_recovery_during_timeout: false
allow_replan_after_timeout: false
allow_partial_blockage_replan: false
use_circumscribed_cost_as_obstruction_threshold: true
plan_inspector:
  # Should be in range [1, 253]. Set to 253 to only consider inscribed and lethal cells as obstructed
  obstruction_threshold: 99
  partial_blockage_path_length_threshold: 5.0