# Input messages
scan_name: "/scan/filtered"
odom_name: "/odom"
map_name: "/map"

# TF frames
laser_frame: "base_scan"
base_link_frame: "base_link"
map_frame: "map"
odom_frame: "odom"

# # This is used for the global localization pose sampler
# Output messages from GL pose sampler 
poses_name: "/gl_sampled_poses"
local_map_name: "/gl_local_map"
sdf_keypoints_name: "/gl_sdf_keypoints"
local_sdf_keypoints_name: "/gl_local_sdf_keypoints"

key_scans_num: 3 #Number of scans used for global localization

# Key scan interval for distance and angle
# These units are meters and degrees.
# If these values are less than 0, global localization is performed for every scan.
key_scan_interval_dist: 0.2
key_scan_interval_yaw: 5.0

# Threshold to detect keypoints
# Keypoints are easily detected if this value is close to zero, but it must be larger than 0.
gradient_square_th: 0.01

# The minimum distance between keypoints and mapped obstacles in meters
# This must be positive.
keypoints_min_dist_from_map: 0.5

# Window size to calculate feature of keypoints in meters
# This must be positive.
sdf_feature_window_size: 1.0

# Threshold to difference between average values of distance fields within the window
# This is used for corresponding keypoint search and correspondences are easily found if this value is large.
# This must be positive.
average_sdf_delta_th: 0.01

# Add random and/or opposite direction samples when global localization candidate poses are found
add_random_samples: true
add_opposite_samples: true

# Number of random samples
random_samples_num: 20

# Positional and angular noises for the random sampling
# These values must be positive.
positional_random_noise: 0.5
angular_random_noise: 0.3

# Threshold to matching rate between scan measurements and a map
# Random samples are easily generated if this value close to 0.
# This value is ignored if less than 0.
matching_rate_th: 0.03
