enable_cart_footprint_publisher: false
default_cart_type: cart0
cart_footprints:
  cart0:
    footprint: [[0.5, 0.3], [-0.5, 0.3], [-0.5, -0.3], [0.5, -0.3]]
    attach_point: [0.5, 0.0]
  cart1:
    footprint: [[0.5, 0.45], [-0.5, 0.45], [-0.5, -0.45], [0.5, -0.45]]
    attach_point: [0.5, 0.0]
robot_footprint: [[0.135, 0.135], [0.135, -0.135], [-0.135, -0.135], [-0.135, 0.135]]
gripper_attach_topic: /gripper/attach
use_gripper_tf: false
gripper_angle_topic: /gripper/angle
gripper_offset_at_zero: [-0.135, 0]
gripper_angle_at_zero: 0.0
publish_footprint_rate: 10
robot_frame: base_link
gripper_frame: gripper
cart_frame: cart
publish_cart_tf: true
costmap_namespaces: [/move_base/global_costmap/set_parameters, /move_base/local_costmap/set_parameters, /costmap_node/costmap/set_parameters]
use_different_planner: false
base_global_planner: movel_global_planner/GlobalPlanner
base_local_planner: teb_local_planner/TebLocalPlannerROS
use_cart_move_base_params: false