#cloud_in: "obstacles_cloud"
#scan: "obstacles_scan"
min_height: -0.165
max_height: 1.0
range_min: 0.02
range_max: 15.0
angle_min: -2 #-0.6
angle_max: 2  #0.6
angle_increment: 0.01745 #0.0006 #0.008725  #0.01745
use_inf: true
# target_frame: "base_link"