cmd_vel_topic: "cmd_vel" #what speed the robot should be traveling at
odom_topic: "odom" #to determine what speed the robot is actually traveling at
status_topic: "/move_base/status" #determine if robot is active in navigating
max_vel_x: 0.3 #maximum linear speed at which robot should move 
max_vel_x_backwards: -0.6
acc_lim_x: 0.50 #acceleration limit in x axis
vel_x_thresh: 0.1 #max threshold difference between desired linear speed and actual linear speed 
max_vel_theta: 0.6 #maximum angular speed
