ignore_obstacle_inside_footprint: true
use_move_base_footprint: true

footprint: [ [0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5,0.5] ] # can be use if use_move_base_footprint is false
# footprint: [ [0.135, 0.135], [0.135, -0.135], [-0.135, -0.135], [-0.135,0.135] ] # can be use if use_move_base_footprint is false